### ISSUE TITLE
Searchview with CoordinatorLayout

### ISSUE THREAD

**Issue by cowfighting** [lapism/SearchView#164]
Hi Lapism,
I would like to achieve similar effect as Google Play with the searchview on its main page. But as this widget is not like a toolbar and it should be above the content I cannot place it inside AppBarLayout.
any solutions?
thanks.

**Comment by lapism** [comment]
Not yet.

**Comment by trivalent** [comment]
Hi cowfighting,

Don't know whats your exact problem is, but I too was not able to use the SearchView with AppBarLayout. My problem was that using this along with appbarlayout was that scrolling on the search results was also triggering appbarlayout scrolling. I was struggling to find out an alternative but I realized that the scroll events are being forwarded to appbarlayout. This is a normal use case when using recyclerview with appbarlayout. But since we don't want the appbarlayout while browsing thru the search result, we must disable nestedscrolling on the recyclerview. You may try disabling the nestedscrolling using this call:  mRecyclerView.setNestedScrollingEnabled(false); initView() function of the SearchView.java in the source code.

Hopefully this helps you or someone else.
