### ISSUE TITLE
suggestion

### ISSUE THREAD

**Issue by JackLauu** [lapism/SearchView#270]
I suggest that the business logic of saving history to database should be included in SearchAdapter itself. I find it in SearchActivity, not very smart. And we can add a attr parameter for saving history or not. Sometimes, SearchView is used for filter listview but not in network, the keyword is refreshed very frequently, and not needed to save.

We can include a 'clear history' button under the recyclerview, when it is not empty it appears.

And more, I don't know the filter feature in SearchView project. I just found it use for change the state of some checkboxs. How to use this?

**Comment by boswelja** [comment]
Hmmm, definitely an interesting idea, although, instead of having a clear history button with the recyclerview, what if we have a way app devs can implement a clear all button into their app settings?
As for filters, yes, it does only change the checkbox state, you need to check for changes with them (which returns a Boolean[] object)

**Comment by JackLauu** [comment]
Yes, that's right.

**Comment by AllanWang** [comment]
The issue with databases is that they need to be consistent, so if you plan on using one with your own attributes, you'll likely need to write the database portions yourself. It's hard to make them generic, which is why lapism might have picked this route.

As for frequent key switches, consider using observables and debouncing your responses.
