### ISSUE TITLE
Capital letter?

### ISSUE THREAD

**Issue by EpsilonOrionis** [lapism/SearchView#73]
I solved the problem that I was facing yesterday, but the issue today is this: Even if the suggestion starts with the capital letter, it is starting with the a lowercase letter

**Comment by lapism** [comment]
It should be like this.

**Comment by EpsilonOrionis** [comment]
I know that I could be annoying, but could you provide a method to choice? Anyway as I wrote, I solved the error that I was facing yesterday by doing a search, so I think that it is related to the HistoryDatabase, and I wasn't using it because I don't need it

**Comment by lapism** [comment]
Not anytime soon, cause I have month with learning to get master degree in front of me.
Of course, this is why I have done the sample app...

**Comment by EpsilonOrionis** [comment]
:smile: one last thing, this problem is related with my layout; when I open the SearchView it matches the whole screen. How can I solve this? I mean how can I tell the SearchView to wrap only its content?

**Comment by lapism** [comment]
setShadow to false :).

**Comment by EpsilonOrionis** [comment]
app:setShadow="false" like this?

**Comment by EpsilonOrionis** [comment]
No, it doesn't work

**Comment by lapism** [comment]
in code setShadow(false) or in app:search_shadow="false"

**Comment by EpsilonOrionis** [comment]
![screenshot_2016-05-10-23-49-31](https://cloud.githubusercontent.com/assets/7190255/15163634/e16b876e-1709-11e6-82ed-a13cb67e5364.png)

**Comment by EpsilonOrionis** [comment]
Please

**Comment by lapism** [comment]
I have functional sample project here and on Play Store. You have so many problems with programming skills, so why you do not check whole project? And I do not understand how you have done this match_parent screen because RecyclerView has now wrap_content functionality. In my project everything works what I know. If something does not work I will fix it soon, but right now I do not know what to fix.
