### ISSUE TITLE
search typed letter not only from beginning

### ISSUE THREAD

**Issue by Rainer-Lang** [lapism/SearchView#8]
eg "Wi-Fi"
It's only suggested if I start with "w".
My suggestion is also search within the suggestions like: "f" -> "Wi-Fi"

**Comment by lapism** [comment]
OK I know what you mean but for now ( from tomorrow ) I will not have a lot of time for improving the library because I am moving to new job and place. But you can fork the project and change it by yourself. It won't be too much complicated. Send me then pull request and I will put it to the master. My suggestion is that everything should be done in adapter.

**Comment by lapism** [comment]
If you won't be able to do it then I will do it in the future, but not soon.

**Comment by Rainer-Lang** [comment]
I wish you all the best and a lot of success in your new job.

OK, I will have a look.

**Comment by lapism** [comment]
Thanks :)

**Comment by brucezz** [comment]
I solved it :)  how to do next ?

**Comment by Rainer-Lang** [comment]
@brucezz Is it possible to make a PR?

**Comment by brucezz** [comment]
@Rainer-Lang   I sent the request just now ,but I don't know whether it works. It's my first time to do so :)

**Comment by Rainer-Lang** [comment]
@brucezz Thanks a lot. Now @lapism has to check and build a new version.

**Comment by lapism** [comment]
thanks a lot. I will upload it after check to jcenter tomorrow.

**Comment by lapism** [comment]
Already done in released 1.3.3. Thanks guys.
